import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO_ROOT = fileURLToPath(new URL('../../../..', import.meta.url));

/** Everything the generators read or write, plus what `tsc` needs. */
const COPIED_ENTRIES = ['app', 'src', 'tsconfig.json', 'package.json'];

/**
 * Runs a generator the same way the CLI does: plain Node (native type stripping) loading
 * `src/system/cli/plopfile.ts`, with the project root as target. Only the interactive prompts are
 * skipped – the answers are passed in directly, so the tests describe the contract between prompts
 * and actions.
 */
const RUNNER = `
import nodePlop from 'node-plop';
const [name, answersJson] = process.argv.slice(1);
const plop = await nodePlop(process.cwd() + '/src/system/cli/plopfile.ts', { destBasePath: process.cwd() });
const result = await plop.getGenerator(name).runActions(JSON.parse(answersJson));
process.stdout.write(JSON.stringify({ failures: result.failures.map((f) => String(f.error)) }));
`;

export type TestProject = {
  root: string;
  run: (generator: string, answers: Record<string, unknown>) => void;
  read: (relativePath: string) => string;
  write: (relativePath: string, content: string) => void;
  readJson: <T = Record<string, unknown>>(relativePath: string) => T;
  exists: (relativePath: string) => boolean;
  typeCheck: () => { ok: boolean; output: string };
  /** Runs `npm run generate` (with `--check`: only checks). */
  generate: (options?: { check?: boolean }) => { ok: boolean; output: string };
  remove: () => void;
};

/** Copies the project into a temporary folder, with `node_modules` symlinked. */
export function createTestProject(): TestProject {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'biberblog-plop-'));
  for (const entry of COPIED_ENTRIES) {
    fs.cpSync(path.join(REPO_ROOT, entry), path.join(root, entry), {
      recursive: true,
      filter: (source) => !source.endsWith('.test.ts'),
    });
  }
  fs.symlinkSync(path.join(REPO_ROOT, 'node_modules'), path.join(root, 'node_modules'), 'dir');
  // The root layout relies on types generated by `next dev`/`next build` (`LayoutProps`), which do
  // not exist here. Pages, modules and the system code are what the generators touch.
  fs.writeFileSync(
    path.join(root, 'tsconfig.plop-test.json'),
    JSON.stringify({
      extends: './tsconfig.json',
      compilerOptions: { incremental: false },
      include: ['src/**/*.ts', 'src/**/*.tsx', 'app/**/page.tsx'],
      exclude: ['node_modules'],
    }),
  );

  const resolve = (relativePath: string) => path.join(root, relativePath);

  return {
    root,
    run(generator, answers) {
      const result = spawnSync(
        process.execPath,
        ['--input-type=module', '-e', RUNNER, generator, JSON.stringify(answers)],
        { cwd: root, encoding: 'utf-8' },
      );
      if (result.status !== 0) {
        throw new Error(`Generator "${generator}" crashed:\n${result.stderr}`);
      }
      const { failures } = JSON.parse(result.stdout) as { failures: string[] };
      if (failures.length > 0) {
        throw new Error(`Generator "${generator}" reported failures:\n${failures.join('\n')}`);
      }
    },
    read: (relativePath) => fs.readFileSync(resolve(relativePath), 'utf-8'),
    write: (relativePath, content) => fs.writeFileSync(resolve(relativePath), content),
    readJson: (relativePath) => JSON.parse(fs.readFileSync(resolve(relativePath), 'utf-8')),
    exists: (relativePath) => fs.existsSync(resolve(relativePath)),
    typeCheck() {
      const result = spawnSync(
        process.execPath,
        [path.join(REPO_ROOT, 'node_modules/typescript/bin/tsc'), '--noEmit', '-p', 'tsconfig.plop-test.json'],
        { cwd: root, encoding: 'utf-8' },
      );

      return { ok: result.status === 0, output: `${result.stdout}${result.stderr}` };
    },
    generate({ check = false } = {}) {
      const result = spawnSync(process.execPath, ['src/system/cli/bin/generate.ts', ...(check ? ['--check'] : [])], {
        cwd: root,
        encoding: 'utf-8',
      });

      return { ok: result.status === 0, output: `${result.stdout}${result.stderr}` };
    },
    remove: () => fs.rmSync(root, { recursive: true, force: true }),
  };
}
