import fs from 'node:fs';
import path from 'node:path';
import { pageContentSchema } from '../content/pageContentSchema.ts';
import { CONTENT_DIR, GENERATED_DIR, MODULES_DIR } from './constants.ts';
import { lowerFirst, pathnameFor, toCamelCase } from './names.ts';

/**
 * Writes the registries in `src/generated/` from their sources – the module folders and the page
 * JSON files. The files are always rewritten completely (never edited), so they cannot drift from
 * their sources. Runs after every CLI command that adds or removes modules/pages, and via
 * `npm run generate` (e.g. after changing a page label by hand).
 */

type GeneratedFile = { path: string; content: string };

const HEADER = '// Generated by `npm run generate` from the module folders and page JSON files – do not edit.\n';

function singleQuoted(value: string): string {
  return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

function listModules(root: string): string[] {
  const modulesDir = path.resolve(root, MODULES_DIR);
  if (!fs.existsSync(modulesDir)) return [];

  return fs
    .readdirSync(modulesDir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory() && fs.existsSync(path.join(modulesDir, entry.name, 'schema.ts')))
    .map((entry) => entry.name)
    .sort();
}

type Page = { slug: string; pathname: string; repoPath: string; label: string };

function listPages(root: string): Page[] {
  const contentDir = path.resolve(root, CONTENT_DIR);
  const pages = fs
    .readdirSync(contentDir, { withFileTypes: true })
    .filter((entry) => entry.isFile() && entry.name.endsWith('.json'))
    .map((entry) => {
      const slug = entry.name.slice(0, -'.json'.length);
      const repoPath = `${CONTENT_DIR}/${entry.name}`;
      const parsed = pageContentSchema.safeParse(JSON.parse(fs.readFileSync(path.join(contentDir, entry.name), 'utf-8')));
      if (!parsed.success) {
        throw new Error(`${repoPath} is not a valid page: ${parsed.error.issues.map((issue) => `${issue.path.join('.')}: ${issue.message}`).join('; ')}`);
      }

      return { slug, pathname: pathnameFor(slug), repoPath, label: parsed.data.label };
    });
  // Home page first, the rest alphabetically.
  return pages.sort((a, b) => (a.slug === 'home' ? -1 : b.slug === 'home' ? 1 : a.slug.localeCompare(b.slug)));
}

function moduleRegistryFile(modules: string[]): string {
  const imports = modules.map(
    (name) => `import { ${lowerFirst(name)}Schema } from '@/src/project/components/modules/${name}/schema';`,
  );
  const entries = modules.map((name) => `  ${name}: { schema: ${lowerFirst(name)}Schema },`);

  return [
    HEADER,
    `import type { ModuleRegistryEntry } from '@/src/system/content/registryTypes';`,
    ...imports,
    '',
    `export const moduleRegistry = {${entries.length > 0 ? `\n${entries.join('\n')}\n` : ''}} satisfies Record<string, ModuleRegistryEntry>;`,
    '',
  ].join('\n');
}

function pageRegistryFile(pages: Page[]): string {
  const imports = pages.map((page) => `import ${toCamelCase(page.slug)}Content from '@/${page.repoPath}';`);
  const entries = pages.map(
    (page) => `  ${singleQuoted(page.pathname)}: { repoPath: ${singleQuoted(page.repoPath)}, content: ${toCamelCase(page.slug)}Content },`,
  );

  return [
    HEADER,
    `import type { PageRegistryEntry } from '@/src/system/content/registryTypes';`,
    ...imports,
    '',
    `export const pageRegistry = {\n${entries.join('\n')}\n} satisfies Record<string, PageRegistryEntry>;`,
    '',
  ].join('\n');
}

function pageLinksFile(pages: Page[]): string {
  const entries = pages.map((page) => `  { pathname: ${singleQuoted(page.pathname)}, label: ${singleQuoted(page.label)} },`);

  return [
    HEADER,
    `import type { PageLink } from '@/src/system/content/registryTypes';`,
    '',
    `export const pageLinks = [\n${entries.join('\n')}\n] as const satisfies readonly PageLink[];`,
    '',
  ].join('\n');
}

/** The generated files as they should be, derived from the current sources. */
export function generatedFiles(root = process.cwd()): GeneratedFile[] {
  const pages = listPages(root);
  if (!pages.some((page) => page.slug === 'home')) {
    throw new Error(`${CONTENT_DIR}/home.json is missing – every project needs a home page.`);
  }
  const modules = listModules(root);

  return [
    { path: `${GENERATED_DIR}/moduleRegistry.ts`, content: moduleRegistryFile(modules) },
    { path: `${GENERATED_DIR}/pageRegistry.ts`, content: pageRegistryFile(pages) },
    { path: `${GENERATED_DIR}/pageLinks.ts`, content: pageLinksFile(pages) },
  ];
}

/** Writes the generated files. Returns the paths that changed. */
export function generate(root = process.cwd()): string[] {
  const changed: string[] = [];
  for (const file of generatedFiles(root)) {
    const target = path.resolve(root, file.path);
    if (fs.existsSync(target) && fs.readFileSync(target, 'utf-8') === file.content) continue;
    fs.mkdirSync(path.dirname(target), { recursive: true });
    fs.writeFileSync(target, file.content);
    changed.push(file.path);
  }

  return changed;
}

/** Paths whose content on disk differs from what `generate()` would write (for CI). */
export function outdatedGeneratedFiles(root = process.cwd()): string[] {
  return generatedFiles(root)
    .filter((file) => {
      const target = path.resolve(root, file.path);
      return !fs.existsSync(target) || fs.readFileSync(target, 'utf-8') !== file.content;
    })
    .map((file) => file.path);
}
