/**
 * Environment variables the editor needs. If one is missing, the editor is disabled and the site
 * runs as a plain static website (`isEditorModeConfigured`). Plain module without Next.js imports,
 * so that `npm run setup` can use it too.
 */

/** Generated by `npm run setup` (or entered by the developer) and added in Vercel. */
export const EDITOR_SECRET_ENV_VARS = ['EDITOR_PASSWORD_HASH', 'EDITOR_SESSION_SECRET', 'GITHUB_TOKEN'] as const;

/** Set by Vercel on deployments; for local development `npm run setup` derives them from the Git remote. */
export const GIT_REPO_ENV_VARS = ['VERCEL_GIT_REPO_OWNER', 'VERCEL_GIT_REPO_SLUG'] as const;

/** Provided by Vercel (blob store connection, OIDC); locally via `vercel env pull .env.local`. */
export const VERCEL_PROVIDED_ENV_VARS = ['BLOB_STORE_ID', 'BLOB_WEBHOOK_PUBLIC_KEY', 'VERCEL_OIDC_TOKEN'] as const;

export const REQUIRED_EDITOR_ENV_VARS = [
  ...EDITOR_SECRET_ENV_VARS,
  ...GIT_REPO_ENV_VARS,
  ...VERCEL_PROVIDED_ENV_VARS,
] as const;
